name: gosec
author: "Bekir Bekirov"
description: "Scan and Send Golang project with Gosec tool"
inputs:
  go-version:
    description: "Go version to use"
    required: false
    default: "1.15"
  send-results:
    description: "Send scan results"
    required: false
    default: "false"
  url:
    description: Scan results collector URL
    required: false
  user:
    description: Collector username
    required: false
  password:
    description: Collector password
    required: false
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - name: Setup Gosec
      shell: bash
      run: |
        go get github.com/securego/gosec/cmd/gosec
    - name: Test, show or send gosec
      shell: bash
      run: |
        if [[ ${{ inputs.send-results }} == true ]]
        then
          gosec -no-fail -fmt=json -out=results.json ./...
          curl --fail -u ${{ inputs.user }}:${{ inputs.password }} \
              -F "repo-name=${{ github.repository }}"  \
              -F "repo-url=${{ github.repositoryUrl }}" \
              -F "scan-type=Gosec Scanner" \
              -F "repo-branch=${{ github.ref_name }}" \
              -F "file=@results.json" \
              ${{ inputs.url }}
        else
          set +e
          gosec -fmt=json -out=results.json ./...
          SCAN_RESULT=$?
          set -e
          echo
          echo "Scan results"
          echo "------------"
          cat results.json
          echo
          exit $SCAN_RESULT
        fi
