name: check-allow-release
author: "Bekir Bekirov"
description: "Define if release to production or reserve cluster allowed"
inputs:
  app-folder:
    description: "Application folder"
    required: false
    default: "."
  deploy-to-rsrv:
    description: 'Deploy to reserve cluster'
    required: false
    default: "true"
  stop-release-filename:
    description: 'If file exists then deploying to production will be omited'
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Define allow release
      working-directory: ${{ inputs.app-folder }}
      shell: bash
      run: |
          RELEASE_TO_PROD=false
          RELEASE_TO_RSRV=false
          if [[ ( "${{ inputs.stop-release-filename }}" == "" || ! -f "${{ inputs.stop-release-filename }}" ) && "${{ github.ref_name }}" == 'master' ]]
          then
            RELEASE_TO_PROD=true
            if [[ "${{ inputs.deploy-to-rsrv }}" == "true" ]]
            then
              RELEASE_TO_RSRV=true
            fi
          fi
          echo "::set-output name=release-to-prod::${RELEASE_TO_PROD}"
          echo "::set-output name=release-to-rsrv::${RELEASE_TO_RSRV}"
          echo "Release to production defined as: ${RELEASE_TO_PROD}"
          echo "Release to reserve defined as: ${RELEASE_TO_RSRV}"
