name: semgrep
author: "Bekir Bekirov"
description: "Scan and Send Java project with Semgrep tool"
inputs:
  send-results:
    description: "Send scan results"
    required: false
    default: "false"
  url:
    description: Scan results collector URL
    required: false
  user:
    description: Collector username
    required: false
  password:
    description: Collector password
    required: false
  token:
    description: Token for rules
    required: true
runs:
  using: composite
  steps:
    - name: Checkout rules
      uses: actions/checkout@v2
      with:
        repository: "PB-Digital/infra-helm-chart"
        ref: refs/heads/master
        token: ${{ inputs.token }}
        path: infra-helm-chart
    - name: Test, show or send
      shell: bash
      run: |
        if [[ ${{ inputs.send-results }} == true ]]
        then
          semgrep --config "infra-helm-chart/semgrep/owasp-top-10-java.yaml" --output results.json --json
          curl --fail -u ${{ inputs.user }}:${{ inputs.password }} \
              -F "repo-name=${{ github.repository }}"  \
              -F "repo-url=${{ github.repositoryUrl }}" \
              -F "scan-type=Semgrep JSON Report" \
              -F "repo-branch=${{ github.ref_name }}" \
              -F "file=@results.json" \
              ${{ inputs.url }}
        else
          semgrep --config "infra-helm-chart/semgrep/owasp-top-10-java.yaml" --error
        fi
