name: java-gradle-build
author: "Bekir Bekirov"
description: "Build Java project with gradle"
inputs:
  app-folder:
    description: "Application folder"
    required: false
    default: "."
  java-distribution:
    description: "Java distribution to use"
    required: false
    default: "temurin"
  java-version:
    description: "Java version to use"
    required: false
    default: "11"
  cache:
    description: "Build tool caching"
    required: false
  build-only:
    description: "Run only build"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.cache }}
    - name: Unit test
      working-directory: ${{ inputs.app-folder }}
      run: |
        if [[ ${{ inputs.build-only }} != true ]]
        then
          gradle test
        fi
      shell: bash
    - name: Package
      working-directory: ${{ inputs.app-folder }}
      run: |
        gradle build -x test
      shell: bash
