name: gradle-send-to-sonar
author: "Bekir Bekirov"
description: "Send to Sonar"
inputs:
  sonar-organization:
    description: "Sonar origanization"
    required: true
  sonar-login:
    description: "Sonar login"
    required: true
  app-folder:
    description: "Application folder"
    required: false
    default: "."
runs:
  using: composite
  steps:
    - id: define-project-key
      name: Define project key
      shell: bash
      run: |
        PROJECT_KEY=${{ github.repository_owner }}_${{ github.event.repository.name }}
        if [[ ${{ inputs.app-folder }} != "." ]]
        then
          PROJECT_KEY="${PROJECT_KEY}_${{ inputs.app-folder }}"
        fi
        echo "Project key defined as: $PROJECT_KEY"
        echo "::set-output name=project-key::$(echo $PROJECT_KEY)"
    - name: Run Sonarqube scanner
      working-directory: ${{ inputs.app-folder }}
      shell: bash
      run: |
        gradle build jacocoTestReport sonarqube \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=${{ inputs.sonar-organization }} \
          -Dsonar.login=${{ inputs.sonar-login }} \
          -Dsonar.projectKey=${{ steps.define-project-key.outputs.project-key }}
