name: python-validate-code
author: "Famil Familzade"
description: "Test Python project"
runs:
  using: composite
  steps:
    - id: install-requirements
      name: "Install requirements && Run tests"
      run: |
        python3 -m venv .venv &&  source .venv/bin/activate && pip install poetry && poetry config virtualenvs.create false && poetry install && pytest --cov=app --cov-report xml:coverage.xml
      shell: bash