name: python-validate-code
author: "Famil Familzade"
description: "Test Python project"
runs:
  using: composite
  steps:
    - id: install-requirements
      name: "Install requirements"
      run: |
        pip3 install --upgrade pip3 && pip3 install poetry && poetry config virtualenvs.create false && poetry install
      shell: bash
    - id: runing-tests
      name: "Running tests"
      run: |
        pytest --cov=app --cov-report xml:coverage.xml
      shell: bash