name: npm-build
author: "Bekir Bekirov"
description: "Build NPM project"
inputs:
  node-version:
    description: "NodeJS version to use"
    required: false
    default: "14"
  build-only:
    description: "Run only build"
    required: false
    default: "false"
  build-dev:
    description: "Run dev build"
    required: false
    default: "false"
  build-prod:
    description: "Run prod build"
    required: false
    default: "false"
  test-only:
    description: "Run only test"
    required: false
    default: "false"
  es-lint:
    description: "Run lint"
    required: false
    default: "true"
  style-lint:
    description: "Run style lint"
    required: false
    default: "true"
  nls-check:
    description: "Run nls-check"
    required: false
    default: "true"
  configure-csp-headers:
    description: "Run configure-csp-headers"
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Build and Test
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      shell: bash
      run: npm install
    - name: Test
      shell: bash
      run: |
        if [[ ${{ inputs.build-only }} != true ]]
        then
          npm run test
        fi
    - name: ESLint
      shell: bash
      run: |
        if [[ ${{ inputs.build-only }} != true ]] && [[ ${{ inputs.es-lint }} == true ]]
        then
          npm run lint
        fi
    - name: Style Lint
      shell: bash
      run: |
        if [[ ${{ inputs.build-only }} != true ]] && [[ ${{ inputs.style-lint }} == true ]]
        then
          npm run stylelint
        fi
    - name: NLS Check
      shell: bash
      run: |
        if [[ ${{ inputs.build-only }} != true ]] && [[ ${{ inputs.nls-check }} == true ]]
        then
          npm run nls-check
        fi
    - name: Config CSP headers
      shell: bash
      run: |
        if [[ ${{ inputs.configure-csp-headers }} == true ]]
        then
          npm run configure-csp-headers
        fi
    - name: Build
      shell: bash
      run: |
        if [[ ${{ inputs.test-only }} != true ]] && [[ ${{ inputs.build-dev }} != true ]] && [[ ${{ inputs.build-prod }} != true ]]
        then
          npm run build
        fi
    - name: Build Dev
      shell: bash
      run: |
        if [[ ${{ inputs.test-only }} != true && [[ ${{ inputs.build-dev }} == true ]]
        then
          npm run build:dev
        fi
    - name: Build Prod
      shell: bash
      run: |
        if [[ ${{ inputs.test-only }} != true && [[ ${{ inputs.build-prod }} == true ]]
        then
          npm run build:prod
        fi
