name: npm
author: "PASHA Bank"
description: "Build, lint, test NPM project"
inputs:
  node-version:
    description: "NodeJS version to use"
    required: false
    default: "14"

  test:
    description: "Run test"
    required: false
    default: "false"

  build:
    description: "Run build"
    required: false
    default: "false"

  lint:
    description: "Run lint"
    required: false
    default: "false"

  style-lint:
    description: "Run stylelint"
    required: false
    default: "false"

  nls-check:
    description: "Run nls check"
    required: false
    default: "false"

  configure-csp-headers:
    description: "Configure CSP headers"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup NodeJS version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Restore npm cache
      uses: actions/cache@v2.1.4
      id: npm-cache
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: npm install
      if: steps.npm-cache.outputs.cache-hit != 'true'

    - name: Test
      shell: bash
      if: inputs.test
      run: npm run test

    - name: Build
      shell: bash
      if: inputs.build
      run: npm run build

    - name: Lint
      shell: bash
      if: inputs.lint
      run: npm run lint

    - name: Stylelint
      shell: bash
      if: inputs.style-lint
      run: npm run lint:style

    - name: NLS check
      shell: bash
      if: inputs.nls-check
      run: npm run nls:check

    - name: Configure CSP headers
      shell: bash
      if: inputs.configure-csp-headers
      run: npm run configure:csp-headers
